Dependencies:
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/extra-cmake-modules': '@stable-kf6'

Options:
  # force installation into the install prefix
  cmake-options: '-DINSTALL_BROKEN_PLYMOUTH_DATA=ON'
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
