#!/usr/bin/env ruby
#--
# SPDX-FileCopyrightText: 2012-2016 Harald Sitter <sitter@kde.org>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
#--

def normalize(value)
  value / 255.0
end

if ARGV.length < 3
  puts('Not enough arguments, need R G B')
  return -1
end

red = normalize(ARGV[0].to_i)
green = normalize(ARGV[1].to_i)
blue = normalize(ARGV[2].to_i)

puts format('%.4f, %.4f, %.4f', red, green, blue)
